name: Build Unity Project (Windows)

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'Name of the Windows build'
        required: false
        default: 'GMTK2025-Windows'
      build_type:
        description: "Choose build type"
        required: true
        default: "Release"
        type: choice
        options:
          - Debug
          - Release

jobs:
  buildForWindows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0  

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            Library-${{ runner.os }}-
      
      - name: Build Unity Project Win64
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Semantic
          buildName: ${{ github.event.inputs.buildName }}
          buildsPath: build
          targetPlatform: StandaloneWindows64
          projectPath: .

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
